[package]
name = "csgoproto"
version = "0.1.5"
authors = ["Laiho"]
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
prost = "0.13.3"
strum = { version = "0.26.3", features = ["derive"] }

[build-dependencies]
prost-build = "0.13.3"